"""
Tag Governance MCP Tool — Lambda Implementation for AgentCore Gateway

Eight tools:
- get_required_tags                 Resolve required-tag policy from caller
                                    input or AWS Organizations Tag Policy.
- list_tag_keys_in_use              Enumerate tag keys actually applied to
                                    resources — starting point for teams
                                    without a formal policy.
- check_tag_compliance              Scan resources, classify compliance.
                                    Default: Resource Explorer + in-Python
                                    classifier. Opt-in: AWS server-side
                                    evaluation via GetResources.
- get_org_tag_compliance_summary    Aggregated counts via GetComplianceSummary.
                                    Cheap rollup — requires an attached
                                    AWS Tag Policy.
- find_untagged_resources           Resource Explorer tag:none query — zero-
                                    tagged resources only (GetResources
                                    cannot return them).
- list_cost_allocation_tag_status   Cost Explorer list_cost_allocation_tags.
                                    Compliance ≠ billing activation. Payer-
                                    only API.
- get_remediation_guidance          Resource Explorer deep-links pre-filtered
                                    to each violation bucket for bulk-fix
                                    via Actions > Manage tags.
- find_resources_by_tag             Resolve a tag selector to a list of
                                    resource ARNs via tag:GetResources.
                                    Used by the cloudwatch-agent to fan out
                                    alarm recommendations across resources
                                    matching a tag.

Design notes:
- Single-account scope. No cross-account role assumption.
- Resource Explorer is the preferred inventory source. No silent fallback
  to the tagging API (which can't return zero-tagged resources).
- Caller-supplied policy is the primary input; AWS Tag Policy is a fallback
  for get_required_tags. AWS-evaluated mode requires an attached policy
  and pre-flights DescribeEffectivePolicy to avoid false-clean results.
- No persistence — policies resolve per-call.

Required IAM Permissions:
- tag:GetResources, tag:GetTagKeys, tag:GetTagValues
- tag:GetComplianceSummary
- ce:ListCostAllocationTags
- organizations:DescribeEffectivePolicy
- resource-explorer-2:ListIndexes, resource-explorer-2:Search
- sts:GetCallerIdentity
"""

from __future__ import annotations

import json
import logging
import os
import urllib.parse
from functools import lru_cache
from typing import Any, Callable

import boto3
from botocore.exceptions import ClientError

# Cross-account support — shared module is packaged alongside handler.py by
# the build (Makefile copies src/lambda/mcp/shared/ into every tool's zip).
# When CROSS_ACCOUNT_ROLE_ARN_TAG_GOVERNANCE is set, get_aws_client returns
# an assumed-role client; otherwise it falls back to the execution role.
from shared.cross_account import get_aws_client

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Commercial AWS partition only.
RESOURCE_EXPLORER_BASE = "https://console.aws.amazon.com/resource-explorer/home"

# GetComplianceSummary + ListCostAllocationTags are global APIs addressed
# only from us-east-1 regardless of deployment region.
_TAG_API_REGION = "us-east-1"
_CE_API_REGION = "us-east-1"

# Resource Explorer Search has a server-side cap of 1000 results per query
# (not paginatable past that).
_RE_SEARCH_HARD_CAP = 1000

# Hint list for the "no policy found" error — never used as a silent default.
SUGGESTED_STARTER_TAGS = ["Environment", "Owner", "CostCentre", "Project"]

# Resource types auto-generated by AWS services and not practically taggable
# by operators (SageMaker auto-ML trial components, default parameter groups,
# AWS-managed docs). Excluded from compliance scans by default; pass
# include_system_managed=true to opt in.
SYSTEM_MANAGED_RESOURCE_TYPES = frozenset({
    "sagemaker:experiment-trial",
    "sagemaker:experiment-trial-component",
    "memorydb:parametergroup",
    "memorydb:user",
    "elasticache:user",
    "rds:og",
    "rds:pg",
    "rds:cluster-snapshot",
    "ssm:document",
    "events:rule",  # many are AWS-managed (e.g. AWSUserNotificationsManagedRule)
    "ec2:network-acl",
    "ec2:dhcp-options",
    "apprunner:autoscalingconfiguration",  # DefaultConfiguration is AWS-owned
    "athena:datacatalog",  # AwsDataCatalog is AWS-owned
    "athena:workgroup",  # primary workgroup is AWS-owned
})


# ---------------------------------------------------------------------------
# Client caching — boto3 clients are reusable within a warm Lambda container.
# ---------------------------------------------------------------------------

@lru_cache(maxsize=None)
def _client(service: str, region: str | None = None):
    """Return a cached boto3 client. Warm-container invocations share clients."""
    return boto3.client(service, region_name=region) if region else boto3.client(service)


@lru_cache(maxsize=1)
def _default_region() -> str:
    """Lambda's home region — AWS_REGION at runtime, falling back to us-east-1."""
    return os.environ.get("AWS_REGION") or _TAG_API_REGION


# ---------------------------------------------------------------------------
# Error translation — one function covers all Tag Policy error shapes that
# both compliance tools can raise.
# ---------------------------------------------------------------------------

def _translate_tag_policy_error(
    exc: Exception, *, mgmt_account_hint: str | None = None
) -> dict[str, Any] | None:
    """Map known ClientError shapes to canonical error payloads.

    Returns None for unmatched errors so the caller can decide whether to
    surface the raw message or treat it as a per-region failure.
    """
    msg = str(exc)
    msg_lower = msg.lower()
    if "constraintviolation" in msg_lower and "enableawsserviceaccess" in msg_lower:
        return {
            "error": (
                "AWS Organizations tag-policies service access is disabled. "
                "Run `aws organizations enable-aws-service-access "
                "--service-principal tagpolicies.tag.amazonaws.com` from the "
                "management account to enable compliance evaluation."
            ),
            "code": "TagPoliciesServiceAccessDisabled",
        }
    if "constraintviolation" in msg_lower and "tag polic" in msg_lower:
        return {
            "error": (
                "No AWS Tag Policy is attached. Compliance evaluation requires "
                "an attached TAG_POLICY — attach one in AWS Organizations, or "
                "use check_tag_compliance with caller-supplied required_tags."
            ),
            "code": "NoTagPoliciesAttached",
        }
    if "AccessDenied" in msg:
        return {"error": mgmt_account_hint or msg}
    return None


# ---------------------------------------------------------------------------
# Organizations — effective Tag Policy fetch (shared between policy resolve
# and the AWS-evaluated preflight).
# ---------------------------------------------------------------------------

def _fetch_effective_tags_block() -> dict[str, Any] | None:
    """Return the parsed 'tags' block from the caller account's effective
    tag policy, or None if no policy / access denied / not in org /
    malformed content. Never raises.
    """
    try:
        account_id = _client("sts").get_caller_identity()["Account"]
        resp = _client("organizations").describe_effective_policy(
            PolicyType="TAG_POLICY", TargetId=account_id
        )
        content = json.loads(resp["EffectivePolicy"]["PolicyContent"])
    except ClientError as exc:
        logger.info(
            "effective tag policy fetch failed: %s",
            exc.response.get("Error", {}).get("Code", str(exc)),
        )
        return None
    except (KeyError, json.JSONDecodeError, TypeError) as exc:
        logger.info("effective tag policy parse failed: %s", exc)
        return None

    tags = content.get("tags")
    return tags if isinstance(tags, dict) and tags else None


def _has_effective_tag_policy() -> bool:
    """True iff caller account has a non-empty effective tag policy."""
    return _fetch_effective_tags_block() is not None


# ---------------------------------------------------------------------------
# Policy resolution
# ---------------------------------------------------------------------------

def _resolve_policy(event: dict[str, Any]) -> dict[str, Any] | None:
    """Return a policy dict or None.

    Shape: {required_tag_keys, allowed_values, case_sensitive, source}.
    source: 'caller' | 'aws_organizations'.
    """
    raw_required = event.get("required_tags")
    raw_allowed = event.get("allowed_values")
    if raw_required or raw_allowed:
        return _parse_caller_policy(raw_required, raw_allowed)
    return _parse_org_policy(_fetch_effective_tags_block())


def _parse_caller_policy(raw_required, raw_allowed_override) -> dict[str, Any] | None:
    """Accept flat list of strings OR list of {key, allowed_values} objects."""
    keys: list[str] = []
    allowed: dict[str, list[str]] = {}

    if isinstance(raw_required, list):
        for item in raw_required:
            if isinstance(item, str):
                keys.append(item)
            elif isinstance(item, dict) and "key" in item:
                keys.append(item["key"])
                if item.get("allowed_values"):
                    allowed[item["key"]] = list(item["allowed_values"])
            else:
                return None  # Wrong item shape
    elif raw_required:
        return None  # Wrong top-level shape (dict, string, etc.)

    # Top-level allowed_values overrides embedded
    if isinstance(raw_allowed_override, dict):
        for k, v in raw_allowed_override.items():
            if k not in keys:
                keys.append(k)
            allowed[k] = list(v)

    if not keys:
        return None
    return {
        "required_tag_keys": sorted(set(keys)),
        "allowed_values": allowed,
        "case_sensitive": {},  # caller-supplied defaults to case-insensitive
        "source": "caller",
    }


def _parse_org_policy(tags_block: dict[str, Any] | None) -> dict[str, Any] | None:
    """Parse Organizations tag-policy 'tags' block into our policy shape."""
    if not tags_block:
        return None

    keys: list[str] = []
    allowed: dict[str, list[str]] = {}
    case_sensitive: dict[str, bool] = {}
    for key, spec in tags_block.items():
        if not isinstance(spec, dict):
            continue
        keys.append(key)
        tag_value = spec.get("tag_value")
        if isinstance(tag_value, dict):
            values = tag_value.get("@@assign")
            if isinstance(values, list) and values:
                allowed[key] = list(values)
        cs = spec.get("case_sensitive")
        if isinstance(cs, dict):
            cs = cs.get("@@assign")
        if isinstance(cs, bool) and cs:
            case_sensitive[key] = True

    if not keys:
        return None
    return {
        "required_tag_keys": sorted(keys),
        "allowed_values": allowed,
        "case_sensitive": case_sensitive,
        "source": "aws_organizations",
    }


# Canonical "no policy" error — used by both get_required_tags and
# check_tag_compliance's in-Python mode.
_NO_POLICY_FOUND_ERROR: dict[str, Any] = {
    "error": "No required-tag policy found.",
    "hint": (
        f"Supply required_tags in the tool input or attach an AWS Organizations "
        f"Tag Policy. Common starter tags: {SUGGESTED_STARTER_TAGS}."
    ),
}


# ---------------------------------------------------------------------------
# Resource Explorer primitives (shared by compliance scan and untagged finder)
# ---------------------------------------------------------------------------

def _re_aggregator_region() -> str | None:
    """Return the Resource Explorer aggregator index region, or None."""
    try:
        client = _client("resource-explorer-2", "us-east-1")
        indexes: list[dict[str, Any]] = []
        for page in client.get_paginator("list_indexes").paginate():
            indexes.extend(page.get("Indexes", []))
    except Exception as exc:  # noqa: BLE001 — any failure means unusable
        logger.warning("Resource Explorer ListIndexes failed: %s", exc)
        return None
    agg = next((i for i in indexes if i.get("Type") == "AGGREGATOR"), None)
    return agg["Region"] if agg else None


def _re_search(
    query_string: str,
    *,
    client: Any,
    limit: int = _RE_SEARCH_HARD_CAP,
) -> tuple[list[dict[str, Any]], bool]:
    """Paginate a Resource Explorer search up to `limit` results.

    Returns (raw_results, api_limit_reached). api_limit_reached is True when
    the server-side 1000-per-query cap is hit, indicating results are
    almost certainly truncated.
    """
    results: list[dict[str, Any]] = []
    cap = min(limit, _RE_SEARCH_HARD_CAP)
    next_token: str | None = None
    while len(results) < cap:
        kwargs: dict[str, Any] = {
            "QueryString": query_string,
            "MaxResults": min(1000, cap - len(results)),
        }
        if next_token:
            kwargs["NextToken"] = next_token
        resp = client.search(**kwargs)
        results.extend(resp.get("Resources", []))
        next_token = resp.get("NextToken")
        if not next_token:
            break
    return results, len(results) >= _RE_SEARCH_HARD_CAP


def _normalise_region(region: str) -> str:
    """Normalise any casing of 'global' / blank to Resource Explorer's 'Global'."""
    return "Global" if not region or region.lower() == "global" else region


# ---------------------------------------------------------------------------
# Resource Explorer result mapping
# ---------------------------------------------------------------------------

def _map_re_result(result: dict[str, Any]) -> dict[str, Any]:
    """Map a Resource Explorer search hit to our internal resource dict."""
    tags: dict[str, str] = {}
    for prop in result.get("Properties") or []:
        if prop.get("Name") == "tags":
            for tag in prop.get("Data") or []:
                tags[tag["Key"]] = tag.get("Value", "")
    return {
        "arn": result.get("Arn", ""),
        "account_id": result.get("OwningAccountId", ""),
        "region": result.get("Region", ""),
        "resource_type": result.get("ResourceType", ""),
        "tags": tags,
    }


def _map_aws_evaluated_result(result: dict[str, Any], region: str) -> dict[str, Any]:
    """Map a GetResources-with-compliance hit into a classification dict.

    AWS ComplianceDetails arrays:
      * NoncompliantKeys             — required tags that are missing
      * KeysWithNoncompliantValues   — required tags whose value isn't allowed
    """
    arn = result.get("ResourceARN", "")
    parts = arn.split(":")
    service = parts[2] if len(parts) > 2 else ""
    account_id = parts[4] if len(parts) > 4 else ""
    resource_part = parts[-1] if parts else ""
    resource_type = (
        f"{service}:{resource_part.split('/')[0]}" if "/" in resource_part else service
    )
    tags = {t["Key"]: t.get("Value", "") for t in result.get("Tags") or []}

    cd = result.get("ComplianceDetails") or {}
    violations: list[dict[str, Any]] = [
        {
            "tag_key": k,
            "violation_type": "missing_tag",
            "expected_values": None,
            "actual_value": tags.get(k),
        }
        for k in cd.get("NoncompliantKeys") or []
    ]
    violations.extend({
        "tag_key": k,
        "violation_type": "invalid_value",
        "expected_values": None,  # AWS does not return the allowed set here
        "actual_value": tags.get(k),
    } for k in cd.get("KeysWithNoncompliantValues") or [])

    return {
        "arn": arn,
        "account_id": account_id,
        "region": region,
        "resource_type": resource_type,
        "existing_tags": tags,
        "compliance_status": "non_compliant" if violations else "compliant",
        "violations": sorted(violations, key=lambda v: v["tag_key"]),
    }


# ---------------------------------------------------------------------------
# Classification (in-Python path)
# ---------------------------------------------------------------------------

def _classify(resource: dict[str, Any], policy: dict[str, Any]) -> dict[str, Any]:
    """Evaluate a resource against the policy. Returns classification dict."""
    violations: list[dict[str, Any]] = []
    for key in policy["required_tag_keys"]:
        actual = resource["tags"].get(key)
        allowed = policy["allowed_values"].get(key) or []
        case_sensitive = policy["case_sensitive"].get(key, False)

        if actual is None:
            violations.append({
                "tag_key": key,
                "violation_type": "missing_tag",
                "expected_values": allowed or None,
                "actual_value": None,
            })
            continue
        if not allowed:
            continue  # Any non-empty value is valid

        if case_sensitive:
            ok = actual in allowed
        else:
            ok = actual.lower() in {v.lower() for v in allowed}
        if not ok:
            violations.append({
                "tag_key": key,
                "violation_type": "invalid_value",
                "expected_values": allowed,
                "actual_value": actual,
            })

    return {
        "arn": resource["arn"],
        "account_id": resource["account_id"],
        "region": resource["region"],
        "resource_type": resource["resource_type"],
        "existing_tags": resource["tags"],
        "compliance_status": "compliant" if not violations else "non_compliant",
        "violations": sorted(violations, key=lambda v: v["tag_key"]),
    }


# ---------------------------------------------------------------------------
# Response assembly — one builder for both evaluation modes.
# ---------------------------------------------------------------------------

def _top_n_counts(values, n: int = 10) -> list[dict[str, Any]]:
    """Top-n most-frequent non-empty values as [{name, count}]."""
    counts: dict[str, int] = {}
    for v in values:
        if not v:
            continue
        counts[v] = counts.get(v, 0) + 1
    ordered = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    return [{"name": name, "count": count} for name, count in ordered[:n]]


def _build_remediation_buckets(
    non_compliant: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Aggregate violations into (tag_key, violation_type, account_id, region,
    resource_type) buckets with counts, sorted by count descending.

    This is small (cardinality = distinct violation combos, typically a few
    dozen) regardless of how many non-compliant resources exist, so it
    survives max_resources truncation and lets remediation prioritise
    correctly.
    """
    counts: dict[tuple, int] = {}
    for c in non_compliant:
        account_id = c.get("account_id", "") or ""
        region = c.get("region", "") or ""
        resource_type = c.get("resource_type", "") or ""
        for v in c.get("violations", []):
            key = (
                v.get("tag_key", ""),
                v.get("violation_type", ""),
                account_id,
                region,
                resource_type,
            )
            counts[key] = counts.get(key, 0) + 1
    ordered = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    return [
        {
            "tag_key": tk,
            "violation_type": vt,
            "account_id": aid,
            "region": reg,
            "resource_type": rt,
            "count": count,
        }
        for (tk, vt, aid, reg, rt), count in ordered
    ]


def _assemble_compliance_response(
    *,
    classifications: list[dict[str, Any]],
    policy: dict[str, Any] | None,
    max_resources: int,
    scan_method: str,
    include_system_managed: bool,
    api_limit_reached: bool = False,
    regions_scanned: list[str] | None = None,
    region_errors: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build the standard check_tag_compliance response from classifications.

    Handles the shared concerns both evaluation modes need:
      - system-managed filtering and accounting
      - optional de-duplication by ARN (Resource Explorer can double-list
        resources visible through multiple views)
      - counts, breakdowns, top-N offenders
      - detail-list truncation
      - api-limit / system-managed / global-resources / region-errors notes
    """
    # Filter system-managed types and record the count.
    system_managed_excluded = 0
    if not include_system_managed:
        kept: list[dict[str, Any]] = []
        for c in classifications:
            if c["resource_type"] in SYSTEM_MANAGED_RESOURCE_TYPES:
                system_managed_excluded += 1
                continue
            kept.append(c)
        classifications = kept

    # De-dupe by ARN (keeps first occurrence).
    seen: set[str] = set()
    deduped: list[dict[str, Any]] = []
    for c in classifications:
        if c["arn"] in seen:
            continue
        seen.add(c["arn"])
        deduped.append(c)
    deduped.sort(key=lambda c: (c["account_id"], c["region"], c["arn"]))

    non_compliant = [c for c in deduped if c["compliance_status"] == "non_compliant"]
    compliant_count = len(deduped) - len(non_compliant)

    by_violation_type = {"missing_tag": 0, "invalid_value": 0}
    # Seed per-tag breakdown from the policy when present so every required
    # key shows up (even the ones with zero violations).
    if policy is not None:
        by_required_tag: dict[str, dict[str, int]] = {
            k: {"missing": 0, "invalid": 0} for k in policy["required_tag_keys"]
        }
    else:
        by_required_tag = {}
    for c in non_compliant:
        for v in c["violations"]:
            by_violation_type[v["violation_type"]] += 1
            bucket = by_required_tag.setdefault(
                v["tag_key"], {"missing": 0, "invalid": 0}
            )
            bucket["missing" if v["violation_type"] == "missing_tag" else "invalid"] += 1

    truncated = len(non_compliant) > max_resources
    aws_evaluated = scan_method == "aws_server_side_evaluation"

    # Aggregate violation buckets from the FULL non_compliant list — NOT
    # from the truncated detail slice. Downstream tools (remediation) use
    # this to prioritise by true impact instead of whatever sample happened
    # to land in non_compliant_resources after truncation.
    remediation_buckets = _build_remediation_buckets(non_compliant)

    result: dict[str, Any] = {
        # AWS-evaluated mode only returns non-compliant resources; compliant
        # counts / compliance_pct aren't knowable from the response.
        "total_resources": None if aws_evaluated else len(deduped),
        "compliant_count": None if aws_evaluated else compliant_count,
        "non_compliant_count": len(non_compliant),
        "compliance_pct": (
            None if aws_evaluated
            else (round(compliant_count / len(deduped) * 100, 1) if deduped else 100.0)
        ),
        "by_violation_type": by_violation_type,
        "by_required_tag": by_required_tag,
        "top_non_compliant_resource_types":
            _top_n_counts(c["resource_type"] for c in non_compliant),
        "top_non_compliant_accounts":
            _top_n_counts(c["account_id"] for c in non_compliant),
        "top_non_compliant_regions":
            _top_n_counts(c["region"] for c in non_compliant),
        "non_compliant_resources": non_compliant[:max_resources],
        "remediation_buckets": remediation_buckets,
        "truncated": truncated,
        "scan_method": scan_method,
        "system_managed_excluded": system_managed_excluded,
    }
    if policy is not None:
        result["effective_policy"] = policy
    if regions_scanned is not None:
        result["regions_scanned"] = regions_scanned
    if region_errors:
        result["region_errors"] = region_errors
    if system_managed_excluded:
        result["system_managed_note"] = (
            f"Excluded {system_managed_excluded} system-managed resource(s) "
            f"(e.g. SageMaker trial components, default parameter groups, "
            f"AWS-managed SSM documents). Pass include_system_managed=true "
            f"to include them."
        )
    if api_limit_reached:
        result["api_limit_reached"] = True
        result["api_limit_note"] = (
            "Resource Explorer Search is capped at 1000 results per query "
            "(AWS-side limit, not paginatable). This scan hit that ceiling, "
            "so the results are almost certainly truncated. Re-run with "
            "resource_types filters (e.g. resource_types=['ec2:instance']) "
            "to narrow the scope and get complete data per type."
        )
    if aws_evaluated:
        result["global_resources_note"] = (
            "AWS server-side evaluation uses a regional API (GetResources). "
            "Global-service resources (IAM roles/users/policies, Route 53 "
            "hosted zones, CloudFront distributions, WAF global rules, etc.) "
            "are NOT included in this scan regardless of which regions you "
            "pass. To evaluate those, use the default in-Python mode, which "
            "queries Resource Explorer and sees global resources."
        )
    return result


# ---------------------------------------------------------------------------
# Tool dispatch
# ---------------------------------------------------------------------------

def handler(event, context):
    logger.info("Event: %s", json.dumps(event, default=str))
    extended_tool_name = context.client_context.custom["bedrockAgentCoreToolName"]
    tool_name = extended_tool_name.split("___")[1]
    logger.info("Tool: %s", tool_name)

    fn = _TOOL_HANDLERS.get(tool_name)
    if not fn:
        return {
            "error": f"Unknown tool: {tool_name}",
            "available_tools": list(_TOOL_HANDLERS.keys()),
        }
    try:
        response = fn(event or {})
        logger.info("Response: %s", json.dumps(response, default=str))
        return response
    except Exception as exc:  # noqa: BLE001 — surface the error to the agent
        logger.exception("Unhandled error in %s", tool_name)
        return {"error": f"{tool_name} failed: {exc}"}


# ---------------------------------------------------------------------------
# Tool 1: get_required_tags
# ---------------------------------------------------------------------------

def handle_get_required_tags(event: dict[str, Any]) -> dict[str, Any]:
    """Resolve required-tag policy from caller input or AWS Organizations."""
    policy = _resolve_policy(event)
    return policy if policy is not None else _NO_POLICY_FOUND_ERROR


# ---------------------------------------------------------------------------
# Tool 2: list_tag_keys_in_use
# ---------------------------------------------------------------------------

def handle_list_tag_keys_in_use(event: dict[str, Any]) -> dict[str, Any]:
    """Return every tag key in use in the caller's account + region."""
    region = event.get("region") or _default_region()
    client = _client("resourcegroupstaggingapi", region)

    keys: list[str] = []
    try:
        for page in client.get_paginator("get_tag_keys").paginate():
            keys.extend(page.get("TagKeys", []))
    except ClientError as exc:
        logger.error("get_tag_keys failed: %s", exc)
        return {"error": str(exc)}

    return {
        "count": len(set(keys)),
        "tag_keys": sorted(set(keys)),
        "region": region,
        "note": (
            "Keys returned are those in use in this account + region. "
            "Use this to seed a required_tags policy, then call "
            "check_tag_compliance with it."
        ),
    }


# ---------------------------------------------------------------------------
# Tool 3: check_tag_compliance
# ---------------------------------------------------------------------------

def handle_check_tag_compliance(event: dict[str, Any]) -> dict[str, Any]:
    """Scan resources and classify against the required-tag policy.

    Modes:
      * Default (in-Python):  Resource Explorer inventory + local classifier.
                              Requires a resolved policy.
      * use_aws_evaluation:   AWS server-side evaluation via GetResources.
                              Requires an attached AWS Tag Policy; caller-
                              supplied required_tags is ignored.
    """
    if event.get("use_aws_evaluation"):
        return _check_compliance_aws_evaluated(event)
    return _check_compliance_in_python(event)


def _check_compliance_in_python(event: dict[str, Any]) -> dict[str, Any]:
    """Resource Explorer inventory + in-Python classifier."""
    policy = _resolve_policy(event)
    if policy is None:
        return _NO_POLICY_FOUND_ERROR

    resource_types = event.get("resource_types") or []
    max_resources = min(int(event.get("max_resources", 25)), 1000)
    include_system_managed = bool(event.get("include_system_managed", False))

    agg_region = _re_aggregator_region()
    if agg_region is None:
        return {
            "status": "resource_explorer_not_indexed",
            "error": (
                "Resource Explorer is not configured with an aggregator index. "
                "Enable it to use the in-Python compliance scan, or pass "
                "use_aws_evaluation=true to evaluate against an attached "
                "AWS Tag Policy instead."
            ),
        }

    # Match-all query is EMPTY STRING. "*" is a free-text search and returns
    # an arbitrary partial slice.
    query = " ".join(f"resourcetype:{t}" for t in resource_types)
    try:
        raw, api_limit_reached = _re_search(
            query, client=_client("resource-explorer-2", agg_region)
        )
    except ClientError as exc:
        logger.error("Resource Explorer Search failed: %s", exc)
        return {
            "status": "resource_explorer_not_indexed",
            "error": f"Resource Explorer search failed: {exc}",
        }

    classifications = [_classify(_map_re_result(r), policy) for r in raw]

    return _assemble_compliance_response(
        classifications=classifications,
        policy=policy,
        max_resources=max_resources,
        scan_method="resource_explorer",
        include_system_managed=include_system_managed,
        api_limit_reached=api_limit_reached,
    )


def _check_compliance_aws_evaluated(event: dict[str, Any]) -> dict[str, Any]:
    """AWS server-side evaluation via GetResources(IncludeComplianceDetails).

    Pre-flights DescribeEffectivePolicy because GetResources silently returns
    zero non-compliant resources when no policy is attached — a false-clean
    result that's indistinguishable from real compliance.
    """
    if not _has_effective_tag_policy():
        return {
            "error": (
                "AWS server-side evaluation requires an attached AWS Tag "
                "Policy on the caller's account (directly or via the OU "
                "tree). No effective policy was found, so GetResources "
                "would silently return zero non-compliant resources and "
                "mislead you. Either attach a Tag Policy in AWS "
                "Organizations, or call without use_aws_evaluation to use "
                "caller-supplied required_tags and the in-Python classifier."
            ),
            "code": "NoTagPoliciesAttached",
        }

    regions = event.get("regions")
    if regions is None:
        regions = [_default_region()]
    elif isinstance(regions, str):
        regions = [regions]

    resource_types = event.get("resource_types") or []
    max_resources = min(int(event.get("max_resources", 25)), 1000)
    include_system_managed = bool(event.get("include_system_managed", False))

    classifications: list[dict[str, Any]] = []
    region_errors: list[dict[str, Any]] = []

    for region in regions:
        params: dict[str, Any] = {
            "IncludeComplianceDetails": True,
            "ExcludeCompliantResources": True,
            "ResourcesPerPage": 100,
        }
        if resource_types:
            params["ResourceTypeFilters"] = resource_types
        try:
            client = _client("resourcegroupstaggingapi", region)
            while True:
                resp = client.get_resources(**params)
                for r in resp.get("ResourceTagMappingList", []):
                    classifications.append(_map_aws_evaluated_result(r, region))
                token = resp.get("PaginationToken") or ""
                if not token:
                    break
                params["PaginationToken"] = token
        except ClientError as exc:
            # Per-region errors don't short-circuit. The preflight already
            # caught the "no policy anywhere" case; if a specific region
            # returns a tag-policy error here it's a region-local quirk.
            region_errors.append({"region": region, "error": str(exc)})

    return _assemble_compliance_response(
        classifications=classifications,
        policy=None,  # AWS-evaluated mode has no local policy object
        max_resources=max_resources,
        scan_method="aws_server_side_evaluation",
        include_system_managed=include_system_managed,
        regions_scanned=regions,
        region_errors=region_errors,
    )


# ---------------------------------------------------------------------------
# Tool 4: get_org_tag_compliance_summary
# ---------------------------------------------------------------------------

def handle_get_org_tag_compliance_summary(event: dict[str, Any]) -> dict[str, Any]:
    """Aggregated compliance counts via GetComplianceSummary.

    Returns counts only (no ARNs, no tags). Requires an attached AWS Tag
    Policy; surfaces a clear error otherwise.
    """
    group_by = event.get("group_by") or ["TARGET_ID"]
    if isinstance(group_by, str):
        group_by = [group_by]

    valid = {"TARGET_ID", "REGION", "RESOURCE_TYPE"}
    invalid = [g for g in group_by if g not in valid]
    if invalid:
        return {"error": f"invalid group_by values: {invalid}. Allowed: {sorted(valid)}"}

    params: dict[str, Any] = {"GroupBy": group_by, "MaxResults": 100}
    for src_key, dst_key in (
        ("account_ids", "TargetIdFilters"),
        ("regions", "RegionFilters"),
        ("resource_types", "ResourceTypeFilters"),
        ("tag_keys", "TagKeyFilters"),
    ):
        val = event.get(src_key)
        if val:
            params[dst_key] = val if isinstance(val, list) else [val]

    client = _client("resourcegroupstaggingapi", _TAG_API_REGION)

    summary_items: list[dict[str, Any]] = []
    try:
        while True:
            resp = client.get_compliance_summary(**params)
            summary_items.extend(resp.get("SummaryList", []))
            token = resp.get("PaginationToken") or ""
            if not token:
                break
            params["PaginationToken"] = token
    except ClientError as exc:
        translated = _translate_tag_policy_error(
            exc,
            mgmt_account_hint=(
                "GetComplianceSummary requires management-account access. "
                "Run this tool from the management (payer) account."
            ),
        )
        if translated is not None:
            return translated
        return {"error": str(exc)}

    total_noncompliant = sum(
        int(it.get("NonCompliantResources", 0) or 0) for it in summary_items
    )
    groups_fully_compliant = sum(
        1 for it in summary_items if int(it.get("NonCompliantResources", 0) or 0) == 0
    )
    return {
        "group_by": group_by,
        "count": len(summary_items),
        "total_noncompliant_resources": total_noncompliant,
        "groups_fully_compliant": groups_fully_compliant,
        "summary": summary_items,
        "region_queried": _TAG_API_REGION,
        "accuracy_caveat": (
            "These numbers are only as complete as your AWS Organizations "
            "Tag Policy configuration. GetComplianceSummary evaluates "
            "ONLY resources within the scope of attached tag policies — "
            "if the policy in the management account does not cover all "
            "required tags, all resource types, and does not use the "
            "enforced_for reporting clause, real non-compliance will be "
            "undercounted or invisible. For a definitive picture, run "
            "check_tag_compliance with caller-supplied required_tags to "
            "scan every resource and classify against your full policy, "
            "or use find_untagged_resources to surface zero-tagged "
            "resources that policy gaps would hide."
        ),
    }


# ---------------------------------------------------------------------------
# Tool 5: find_untagged_resources
# ---------------------------------------------------------------------------

def handle_find_untagged_resources(event: dict[str, Any]) -> dict[str, Any]:
    """Resource Explorer ``tag:none`` query — zero-tagged resources.

    Paginates up to min(limit, 1000) — Resource Explorer Search's server-side
    ceiling. Single resource_type and single region filters are pushed into
    the query server-side so the cap is less likely to bite.
    """
    account_ids = event.get("account_ids")
    regions = event.get("regions")
    resource_types = event.get("resource_types")
    limit = min(int(event.get("limit", _RE_SEARCH_HARD_CAP)), _RE_SEARCH_HARD_CAP)

    if isinstance(account_ids, str):
        account_ids = [account_ids]
    if isinstance(regions, str):
        regions = [regions]
    if isinstance(resource_types, str):
        resource_types = [resource_types]

    agg_region = _re_aggregator_region()
    if agg_region is None:
        return {
            "status": "resource_explorer_not_indexed",
            "message": (
                "Resource Explorer is not enabled in this account — "
                "enable an aggregator index to use this tool. Non-fatal."
            ),
        }

    # Push single-value filters into the query server-side. Multi-value
    # filters (and account_ids, which has no query syntax) fall back to
    # post-filter after pagination.
    query_parts = ["tag:none"]
    if resource_types and len(resource_types) == 1:
        query_parts.append(f"resourcetype:{resource_types[0]}")
    if regions and len(regions) == 1:
        query_parts.append(f"region:{_normalise_region(regions[0])}")

    try:
        raw, api_limit_reached = _re_search(
            " ".join(query_parts),
            client=_client("resource-explorer-2", agg_region),
            limit=limit,
        )
    except ClientError as exc:
        msg = str(exc)
        if "ValidationException" in msg:
            return {
                "status": "resource_explorer_not_indexed",
                "message": (
                    "Resource Explorer query failed — aggregator index may "
                    "not be enabled. Non-fatal."
                ),
            }
        return {"error": msg}

    # Post-filter for multi-value filters and account_ids.
    results: list[dict[str, Any]] = []
    for r in raw:
        owning_acct = r.get("OwningAccountId", "")
        r_region = r.get("Region", "")
        r_type = r.get("ResourceType", "")
        if account_ids and owning_acct not in account_ids:
            continue
        if regions and r_region not in regions:
            continue
        if resource_types and r_type not in resource_types:
            continue
        results.append({
            "resource_arn": r.get("Arn", ""),
            "account_id": owning_acct,
            "region": r_region,
            "resource_type": r_type,
            "service": r.get("Service", ""),
        })

    out: dict[str, Any] = {
        "status": "ok",
        "count": len(results),
        "raw_count": len(raw),
        "resources": results,
        "filter_applied": {
            "account_ids": account_ids or [],
            "regions": regions or [],
            "resource_types": resource_types or [],
        },
    }
    if api_limit_reached:
        out["api_limit_reached"] = True
        out["api_limit_note"] = (
            "Resource Explorer Search is capped at 1000 results per query "
            "(AWS-side limit, not paginatable). This scan hit that ceiling, "
            "so there may be more untagged resources not shown. Narrow the "
            "scope by passing a single resource_type or region so the server "
            "can filter before hitting the cap."
        )
    return out


# ---------------------------------------------------------------------------
# Tool 6: list_cost_allocation_tag_status
# ---------------------------------------------------------------------------

def handle_list_cost_allocation_tag_status(event: dict[str, Any]) -> dict[str, Any]:
    """Cost Explorer list_cost_allocation_tags — payer-only API.

    Compliance does NOT imply billing activation. This surfaces which tags
    are actually usable in Cost Explorer / CUR.
    """
    params: dict[str, Any] = {"MaxResults": 100}
    if event.get("status"):
        params["Status"] = event["status"]
    if event.get("type"):
        params["Type"] = event["type"]

    client = _client("ce", _CE_API_REGION)
    tags: list[dict[str, Any]] = []
    try:
        while True:
            resp = client.list_cost_allocation_tags(**params)
            for t in resp.get("CostAllocationTags", []):
                tags.append({
                    "tag_key": t.get("TagKey", ""),
                    "status": t.get("Status", ""),
                    "type": t.get("Type", ""),
                    "last_used_date": str(t.get("LastUsedDate", "")),
                })
            token = resp.get("NextToken") or ""
            if not token:
                break
            params["NextToken"] = token
    except ClientError as exc:
        if "AccessDenied" in str(exc):
            return {
                "error": (
                    "list_cost_allocation_tags is a payer-only API. Run "
                    "this tool from the management (payer) account."
                ),
            }
        return {"error": str(exc)}

    active = sum(1 for t in tags if t["status"] == "Active")
    return {
        "count": len(tags),
        "active_count": active,
        "inactive_count": len(tags) - active,
        "tags": tags,
    }


# ---------------------------------------------------------------------------
# Tool 7: get_remediation_guidance
# ---------------------------------------------------------------------------

def handle_get_remediation_guidance(event: dict[str, Any]) -> dict[str, Any]:
    """Generate Resource Explorer deep-links bucketed by violation scope.

    Each link pre-filters Resource Explorer to exactly one bucket of
    (region, resource_type, tag_key, violation_type). Operator workflow:
    open link, select resources, Actions > Manage tags.

    Links are returned sorted by bucket size (most resources first) so the
    caller can surface the highest-impact fixes first. Capped at
    ``max_links`` (default 20) with a truncation flag when exceeded —
    prevents flooding the agent's context with low-impact buckets.

    Input: prefers ``remediation_buckets`` (aggregated, complete across the
    full scan, small regardless of account size). Falls back to
    ``non_compliant_resources`` (per-resource, may be truncated by
    check_tag_compliance's max_resources cap) for backwards compatibility.

    Self-contained fallback: if NEITHER ``remediation_buckets`` NOR
    ``non_compliant_resources`` is supplied, this tool runs
    check_tag_compliance internally (passing the same event through, so
    required_tags / use_aws_evaluation / resource_types / regions all apply)
    and uses the buckets it produces. This lets a planner that can't thread a
    prior tool's JSON output back in (e.g. Amazon Quick) call
    get_remediation_guidance standalone. Mirrors assess_dx_resiliency, which
    fetches its own topology when none is passed.
    """
    scan_method = event.get("scan_method", "resource_explorer")
    max_links = max(1, int(event.get("max_links", 20)))

    # Self-contained fallback: no buckets AND no per-resource list → run the
    # compliance scan ourselves to regenerate buckets. The internal scan must
    # finish within the caller's invocation timeout; for normally-sized
    # accounts this is well under the limit.
    if not event.get("remediation_buckets") and not event.get("non_compliant_resources"):
        compliance = handle_check_tag_compliance(event)
        # Propagate non-success responses verbatim (no policy, RE not indexed,
        # payer-only errors) so the caller sees the actionable hint, not an
        # empty link list.
        if compliance.get("error") or compliance.get("status") not in (None, "ok"):
            return compliance
        event = {
            **event,
            "remediation_buckets": compliance.get("remediation_buckets", []),
            # Use the scan's actual method so the invalid_value caveat is correct.
            "scan_method": compliance.get("scan_method", scan_method),
        }
        scan_method = event["scan_method"]

    # Prefer pre-aggregated buckets — they reflect the full scan, not a
    # truncated sample. Fall back to reconstructing from non_compliant_resources
    # only if buckets aren't supplied (e.g. older agent prompts).
    buckets_input = event.get("remediation_buckets")
    if buckets_input:
        buckets = [
            (
                (
                    b.get("tag_key", ""),
                    b.get("violation_type", ""),
                    b.get("account_id", "") or "",
                    b.get("region", "") or "",
                    b.get("resource_type", "") or "",
                ),
                int(b.get("count", 0) or 0),
            )
            for b in buckets_input
            if int(b.get("count", 0) or 0) > 0
        ]
    else:
        non_compliant = event.get("non_compliant_resources", [])
        if not non_compliant:
            return {
                "summary": (
                    "All scanned resources are compliant. No remediation needed."
                ),
                "links": [],
            }
        buckets = [
            (
                (b["tag_key"], b["violation_type"], b["account_id"],
                 b["region"], b["resource_type"]),
                b["count"],
            )
            for b in _build_remediation_buckets(non_compliant)
        ]

    if not buckets:
        return {
            "summary": "All scanned resources are compliant. No remediation needed.",
            "links": [],
        }

    # Pre-sort defensively; buckets from _build_remediation_buckets are
    # already ordered, but caller-supplied remediation_buckets may not be.
    ordered = sorted(buckets, key=lambda kv: (-kv[1], kv[0]))
    total_buckets = len(ordered)
    shown = ordered[:max_links]

    links = [
        _build_re_remediation_link(
            tag_key=tk, violation_type=vt, account_id=aid,
            region=reg, resource_type=rt, count=count,
        )
        for (tk, vt, aid, reg, rt), count in shown
    ]

    total_missing = sum(
        c for (_tk, vt, _aid, _reg, _rt), c in ordered if vt == "missing_tag"
    )
    total_invalid = sum(
        c for (_tk, vt, _aid, _reg, _rt), c in ordered if vt == "invalid_value"
    )
    parts: list[str] = []
    if total_missing:
        parts.append(f"{total_missing} violation(s) for missing required tags")
    if total_invalid:
        parts.append(f"{total_invalid} violation(s) for invalid tag values")
    summary = (
        f"{', '.join(parts)}. Links are ordered by bucket size (most "
        f"resources first). Each link opens AWS Resource Explorer "
        f"pre-filtered to exactly one (region, resource_type, tag_key) "
        f"bucket. In the console: select the resources, then Actions > "
        f"Manage tags to add or correct the tag in bulk."
    )
    if scan_method == "aws_server_side_evaluation":
        summary += (
            " Note: scan used AWS server-side evaluation; expected_values are "
            "not returned by that API, so invalid_value links let you inspect "
            "the current values rather than pre-filtering by them."
        )

    result: dict[str, Any] = {
        "summary": summary,
        "links": links,
        "total_buckets": total_buckets,
    }
    if total_buckets > max_links:
        result["links_truncated"] = True
        result["links_dropped"] = total_buckets - max_links
        result["links_truncation_note"] = (
            f"Showing the top {max_links} highest-impact buckets out of "
            f"{total_buckets} total. Re-run with max_links=<N> to see more, "
            f"or narrow the scope by passing resource_types or regions to "
            f"the preceding check_tag_compliance call."
        )
    return result


def _build_re_remediation_link(
    *, tag_key: str, violation_type: str, account_id: str,
    region: str, resource_type: str, count: int,
) -> dict[str, Any]:
    """Compose one Resource Explorer deep-link for a violation bucket.

    Query filters (space-separated, AND):
      * missing_tag   : -tag.key:<tag_key>
      * invalid_value :  tag.key:<tag_key>
      * region        :  region:<region>      ("Global" for global services)
      * resource_type :  resourcetype:<type>  (e.g. iam:role, s3:bucket)
    """
    region_filter = _normalise_region(region)
    tag_filter = (
        f"-tag.key:{tag_key}" if violation_type == "missing_tag"
        else f"tag.key:{tag_key}"
    )
    query_parts = [tag_filter, f"region:{region_filter}"]
    if resource_type:
        query_parts.append(f"resourcetype:{resource_type}")
    # quote_plus matches the AWS console's own wire format (spaces as "+").
    encoded = urllib.parse.quote_plus(" ".join(query_parts))
    url = f"{RESOURCE_EXPLORER_BASE}?region=us-east-1#/search?query={encoded}"

    if violation_type == "missing_tag":
        description = (
            f"Add '{tag_key}' tag to {count} {resource_type} resource(s) in "
            f"{region_filter} (account {account_id}). Open link, select all, "
            f"Actions > Manage tags > Add new tag."
        )
    else:
        description = (
            f"Correct '{tag_key}' value on {count} {resource_type} resource(s) "
            f"in {region_filter} (account {account_id}). Open link, inspect "
            f"current values, select affected resources, Actions > Manage tags."
        )

    return {
        "kind": "resource_explorer",
        "url": url,
        "description": description,
        "tag_key": tag_key,
        "violation_type": violation_type,
        "account_id": account_id,
        "region": region_filter,
        "resource_type": resource_type,
        "resource_count": count,
    }


# ---------------------------------------------------------------------------
# Tool 8: find_resources_by_tag
# ---------------------------------------------------------------------------

# 1000-resource cap matches the cloudwatch-agent's contract — beyond that the
# agent's per-resource alarm-recommendation fan-out becomes unwieldy. The cap
# is enforced in Python (we stop paginating once we hit it) rather than via
# the boto3 ResourcesPerPage knob, which only controls page size.
_FIND_RESOURCES_HARD_CAP = 1000

_FIND_RESOURCES_TRUNCATION_NOTE = (
    f"Results capped at {_FIND_RESOURCES_HARD_CAP}. Provide more specific "
    f"tag_filters or a resource_types filter to narrow results."
)


def _build_tag_filters(raw: dict[str, Any]) -> list[dict[str, Any]]:
    """Convert a {key: value} or {key: [values]} dict into the boto3 shape.

    boto3 ``tag:GetResources`` expects ``TagFilters=[{"Key": ..., "Values":
    [...]}]``. The user's input may be either ``{"App": "test"}`` (single
    value) or ``{"App": ["test", "prod"]}`` (multi-value, valid AWS query
    semantics — OR within a key). Both are passed through here.

    Skips entries whose key is empty/falsy. Coerces non-list values into a
    one-element list of the stringified value.
    """
    filters: list[dict[str, Any]] = []
    for key, value in raw.items():
        if not key:
            continue
        if isinstance(value, list):
            values = [str(v) for v in value]
        elif value is None:
            values = []
        else:
            values = [str(value)]
        filters.append({"Key": str(key), "Values": values})
    return filters


def _resource_from_arn(
    raw_resource: dict[str, Any], fallback_region: str
) -> dict[str, Any]:
    """Map one ``ResourceTagMappingList`` entry to our return shape.

    ``tag:GetResources`` returns ``ResourceARN`` and ``Tags`` (list of
    ``{"Key", "Value"}``) — nothing else. We extract ``account_id`` and
    ``region`` by parsing the ARN, falling back to ``fallback_region``
    (the Lambda's query region) for global-service ARNs whose ARN has an
    empty region segment.

    ARN format: ``arn:aws:<service>:<region>:<account>:<rest>``.
    """
    arn = raw_resource.get("ResourceARN", "") or ""
    parts = arn.split(":")
    region = parts[3] if len(parts) > 3 and parts[3] else fallback_region
    account_id = parts[4] if len(parts) > 4 else ""
    tags = {
        t.get("Key", ""): t.get("Value", "")
        for t in raw_resource.get("Tags") or []
        if t.get("Key")
    }
    return {
        "arn": arn,
        "tags": tags,
        "region": region,
        "account_id": account_id,
    }


def handle_find_resources_by_tag(event: dict[str, Any]) -> dict[str, Any]:
    """Resolve a tag selector to a list of resource ARNs via tag:GetResources.

    Designed for the cloudwatch-agent's "alarms for tag App=test" flow: the
    agent calls this tool first to get ARNs, then fans out to
    ``cloudwatch.get_recommended_metric_alarms`` per resource.

    Inputs:
      * ``tag_filters`` (required, dict): ``{"App": "test"}`` or
        ``{"App": ["test", "prod"]}``. Empty/missing returns the canonical
        ``selector_required`` error so the agent can prompt the user.
      * ``resource_types`` (optional, list[str]): ``["ec2:instance",
        "lambda:function"]`` — passed through to ``ResourceTypeFilters``.
      * ``region`` (optional, str): defaults to the Lambda's ``AWS_REGION``.

    Pagination caps results at 1000 (per Requirement 3.3). When the cap is
    hit, ``truncated`` flips to True and a ``note`` field carries a hint to
    narrow filters. When not hit, ``note`` is None.

    Cross-account: routed through ``shared.cross_account.get_aws_client``
    with ``role_alias="TAG_GOVERNANCE"``, so it inherits whatever
    ``CROSS_ACCOUNT_ROLE_ARN_TAG_GOVERNANCE`` is configured for the rest of
    this Lambda. Unset = falls back to the execution role.
    """
    raw_filters = event.get("tag_filters")
    if not isinstance(raw_filters, dict) or not raw_filters:
        return {
            "error": "selector_required",
            "message": "Provide at least one tag_filters entry.",
        }

    tag_filters = _build_tag_filters(raw_filters)
    if not tag_filters:
        # The dict was non-empty but every entry had a falsy key.
        return {
            "error": "selector_required",
            "message": "Provide at least one tag_filters entry.",
        }

    resource_types = event.get("resource_types") or []
    if isinstance(resource_types, str):
        resource_types = [resource_types]

    region = event.get("region") or _default_region()

    client = get_aws_client(
        service_name="resourcegroupstaggingapi",
        region_name=region,
        role_alias="TAG_GOVERNANCE",
    )

    params: dict[str, Any] = {
        "TagFilters": tag_filters,
        "ResourcesPerPage": 100,
    }
    if resource_types:
        params["ResourceTypeFilters"] = list(resource_types)

    resources: list[dict[str, Any]] = []
    truncated = False
    try:
        while True:
            resp = client.get_resources(**params)
            for raw in resp.get("ResourceTagMappingList", []):
                if len(resources) >= _FIND_RESOURCES_HARD_CAP:
                    truncated = True
                    break
                resources.append(_resource_from_arn(raw, region))
            if truncated:
                break
            token = resp.get("PaginationToken") or ""
            if not token:
                break
            params["PaginationToken"] = token
    except ClientError as exc:
        logger.error("tag:GetResources failed: %s", exc)
        return {"error": str(exc)}

    return {
        "resources": resources,
        "truncated": truncated,
        "note": _FIND_RESOURCES_TRUNCATION_NOTE if truncated else None,
    }


# ---------------------------------------------------------------------------
# Tool registry — declared at module scope so the dispatcher can find handlers.
# ---------------------------------------------------------------------------

_TOOL_HANDLERS: dict[str, Callable[[dict[str, Any]], dict[str, Any]]] = {
    "get_required_tags": handle_get_required_tags,
    "list_tag_keys_in_use": handle_list_tag_keys_in_use,
    "check_tag_compliance": handle_check_tag_compliance,
    "get_org_tag_compliance_summary": handle_get_org_tag_compliance_summary,
    "find_untagged_resources": handle_find_untagged_resources,
    "list_cost_allocation_tag_status": handle_list_cost_allocation_tag_status,
    "get_remediation_guidance": handle_get_remediation_guidance,
    "find_resources_by_tag": handle_find_resources_by_tag,
}
